version: "3.8"

services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8080"

  product-service:
    build: ./product-service
    ports:
      - "8082:8080"

  order-service:
    build: ./order-service
    ports:
      - "8083:8080"

  payment-service:
    build: ./payment-service
    ports:
      - "8084:8080"
