apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-pvc
  labels:
    app.kubernetes.io/name: msa-shop
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: mysql
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: mysql
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          ports:
            - containerPort: 3306
          resources:
            {{- toYaml (default .Values.defaultResources .Values.mysql.resources) | nindent 12 }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: mysql-root-password
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "no"
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: init
              mountPath: /docker-entrypoint-initdb.d
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - 'mysqladmin ping -h localhost -uroot -p"$MYSQL_ROOT_PASSWORD"'
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 15
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - 'mysqladmin ping -h localhost -uroot -p"$MYSQL_ROOT_PASSWORD"'
            initialDelaySeconds: 25
            periodSeconds: 10
            timeoutSeconds: 15
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - 'mysqladmin ping -h localhost -uroot -p"$MYSQL_ROOT_PASSWORD"'
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 15
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mysql-pvc
        - name: init
          configMap:
            name: {{ .Release.Name }}-mysql-init
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: mysql
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
